[package]
name = "code009"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"